default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: chat_basket_development
  username: chat_basket

test:
  <<: *default
  database: chat_basket_test
  username: chat_basket

production:
  <<: *default
